package com.myspace.kbs_happydonia.communicationstrategyissues;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GoalIssue implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String type;

	private int communicationStrategyId;

	public GoalIssue() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public int getCommunicationStrategyId() {
		return this.communicationStrategyId;
	}

	public void setCommunicationStrategyId(int communicationStrategyId) {
		this.communicationStrategyId = communicationStrategyId;
	}

	public GoalIssue(java.lang.String type, int communicationStrategyId) {
		this.type = type;
		this.communicationStrategyId = communicationStrategyId;
	}

}