package com.myspace.kbs_happydonia.communicationstrategyissues;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class JustificationIssue implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int communicationStrategyId;

	private java.lang.String issueMotive;

	public JustificationIssue() {
	}

	public int getCommunicationStrategyId() {
		return this.communicationStrategyId;
	}

	public void setCommunicationStrategyId(int communicationStrategyId) {
		this.communicationStrategyId = communicationStrategyId;
	}

	public java.lang.String getIssueMotive() {
		return this.issueMotive;
	}

	public void setIssueMotive(java.lang.String issueMotive) {
		this.issueMotive = issueMotive;
	}

	public JustificationIssue(int communicationStrategyId,
			java.lang.String issueMotive) {
		this.communicationStrategyId = communicationStrategyId;
		this.issueMotive = issueMotive;
	}

}