package com.myspace.kbs_happydonia.communicationstrategyissues;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LowOverallReactions implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int communicationStrategyId;

	public LowOverallReactions() {
	}

	public int getCommunicationStrategyId() {
		return this.communicationStrategyId;
	}

	public void setCommunicationStrategyId(int communicationStrategyId) {
		this.communicationStrategyId = communicationStrategyId;
	}

	public LowOverallReactions(int communicationStrategyId) {
		this.communicationStrategyId = communicationStrategyId;
	}

}