package com.myspace.kbs_happydonia.communicationstrategygoals;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Difusion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int communicationStrategyId;

	public Difusion() {
	}

	public int getCommunicationStrategyId() {
		return this.communicationStrategyId;
	}

	public void setCommunicationStrategyId(int communicationStrategyId) {
		this.communicationStrategyId = communicationStrategyId;
	}

	public Difusion(int communicationStrategyId) {
		this.communicationStrategyId = communicationStrategyId;
	}

}