package com.myspace.kbs_happydonia;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Activity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int id;
	private int communicationStrategyId;
	private java.lang.String contentType;
	private int views;
	private int reactions;
	private java.lang.String publicationDay;

	private java.lang.Boolean processed;

	public Activity() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getCommunicationStrategyId() {
		return this.communicationStrategyId;
	}

	public void setCommunicationStrategyId(int communicationStrategyId) {
		this.communicationStrategyId = communicationStrategyId;
	}

	public java.lang.String getContentType() {
		return this.contentType;
	}

	public void setContentType(java.lang.String contentType) {
		this.contentType = contentType;
	}

	public int getViews() {
		return this.views;
	}

	public void setViews(int views) {
		this.views = views;
	}

	public int getReactions() {
		return this.reactions;
	}

	public void setReactions(int reactions) {
		this.reactions = reactions;
	}

	public java.lang.String getPublicationDay() {
		return this.publicationDay;
	}

	public void setPublicationDay(java.lang.String publicationDay) {
		this.publicationDay = publicationDay;
	}

	public java.lang.Boolean getProcessed() {
		return this.processed;
	}

	public void setProcessed(java.lang.Boolean processed) {
		this.processed = processed;
	}

	public Activity(int id, int communicationStrategyId,
			java.lang.String contentType, int views, int reactions,
			java.lang.String publicationDay, java.lang.Boolean processed) {
		this.id = id;
		this.communicationStrategyId = communicationStrategyId;
		this.contentType = contentType;
		this.views = views;
		this.reactions = reactions;
		this.publicationDay = publicationDay;
		this.processed = processed;
	}

}