package com.myspace.kbs_happydonia;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CommunicationStrategy implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int communicationPlanId;
	private java.lang.String goal;
	private java.util.List<java.lang.String> planification;
	private java.util.List<java.lang.String> targetAudience;
	private java.util.List<com.myspace.kbs_happydonia.Activity> activityList;

	private int id;

	private int planStrategyNumber;

	private int mva;

	private java.lang.Double conversionRate;

	private java.lang.Boolean goalAchieved;

	public CommunicationStrategy() {
	}

	public int getCommunicationPlanId() {
		return this.communicationPlanId;
	}

	public void setCommunicationPlanId(int communicationPlanId) {
		this.communicationPlanId = communicationPlanId;
	}

	public java.lang.String getGoal() {
		return this.goal;
	}

	public void setGoal(java.lang.String goal) {
		this.goal = goal;
	}

	public java.util.List<java.lang.String> getPlanification() {
		return this.planification;
	}

	public void setPlanification(java.util.List<java.lang.String> planification) {
		this.planification = planification;
	}

	public java.util.List<java.lang.String> getTargetAudience() {
		return this.targetAudience;
	}

	public void setTargetAudience(
			java.util.List<java.lang.String> targetAudience) {
		this.targetAudience = targetAudience;
	}

	public java.util.List<com.myspace.kbs_happydonia.Activity> getActivityList() {
		return this.activityList;
	}

	public void setActivityList(
			java.util.List<com.myspace.kbs_happydonia.Activity> activityList) {
		this.activityList = activityList;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getPlanStrategyNumber() {
		return this.planStrategyNumber;
	}

	public void setPlanStrategyNumber(int planStrategyNumber) {
		this.planStrategyNumber = planStrategyNumber;
	}

	public int getMva() {
		return this.mva;
	}

	public void setMva(int mva) {
		this.mva = mva;
	}

	public java.lang.Double getConversionRate() {
		return this.conversionRate;
	}

	public void setConversionRate(java.lang.Double conversionRate) {
		this.conversionRate = conversionRate;
	}

	public java.lang.Boolean getGoalAchieved() {
		return this.goalAchieved;
	}

	public void setGoalAchieved(java.lang.Boolean goalAchieved) {
		this.goalAchieved = goalAchieved;
	}

	public CommunicationStrategy(int communicationPlanId,
			java.lang.String goal,
			java.util.List<java.lang.String> planification,
			java.util.List<java.lang.String> targetAudience,
			java.util.List<com.myspace.kbs_happydonia.Activity> activityList,
			int id, int planStrategyNumber, int mva,
			java.lang.Double conversionRate, java.lang.Boolean goalAchieved) {
		this.communicationPlanId = communicationPlanId;
		this.goal = goal;
		this.planification = planification;
		this.targetAudience = targetAudience;
		this.activityList = activityList;
		this.id = id;
		this.planStrategyNumber = planStrategyNumber;
		this.mva = mva;
		this.conversionRate = conversionRate;
		this.goalAchieved = goalAchieved;
	}

}