package com.myspace.kbs_happydonia;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CommunicationPlan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String goal;
	private java.util.List<com.myspace.kbs_happydonia.CommunicationStrategy> communicationStrategyList;
	private int id;

	public CommunicationPlan() {
	}

	public java.lang.String getGoal() {
		return this.goal;
	}

	public void setGoal(java.lang.String goal) {
		this.goal = goal;
	}

	public java.util.List<com.myspace.kbs_happydonia.CommunicationStrategy> getCommunicationStrategyList() {
		return this.communicationStrategyList;
	}

	public void setCommunicationStrategyList(
			java.util.List<com.myspace.kbs_happydonia.CommunicationStrategy> communicationStrategyList) {
		this.communicationStrategyList = communicationStrategyList;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CommunicationPlan(
			java.lang.String goal,
			java.util.List<com.myspace.kbs_happydonia.CommunicationStrategy> communicationStrategyList,
			int id) {
		this.goal = goal;
		this.communicationStrategyList = communicationStrategyList;
		this.id = id;
	}

}